name: Feature request / Enhancement
description: Request or propose a new feature/enhancement
labels: "kind/enhancement"
body:
  - type: textarea
    validations:
      required: true
    attributes:
      label: Reason/Context
      description: >-
        Please try answering a few of those questions:
          * Why we need this improvement?
          * How will this change help?
          * What is the motivation?
  - type: textarea
    validations:
      required: true
    attributes:
      label: Description
      description: >-
        Describe the feature or enhancement here.
        
        What changes have to be introduced? Will this be a breaking change?
  - type: textarea
    attributes:
      label: Implementation ideas
      description: >-
        If you have any implementation ideas, they can go here.
